info:
  app.name: @project.name@
  app.description: @project.description@
  app.version: @project.version@

server:
  port: 8088

management:
  endpoint.shutdown.enabled: true
  endpoints.web.exposure.include: '*'

spring.profiles.active: native
#spring.cloud.config.server.native.searchLocations=file://${user.home}/MicroService/centralProperties/

endpoints:
  shutdown:
    enabled: true
